### ISSUE TITLE
Restrict Context Access by Branch Name

### ISSUE THREAD

**Issue by eddiewebb** [CircleCI-Public/circle-policy-agent#33]
This is the "Branch Based Secrets" we all want and love.

Included in playground as example. This ticket is to make the branch name an argument, and move to `config` package.

@davidmdm  - hope your ok if I track the things we're interested in collabing on here?

**Comment by davidmdm** [comment]
Of course !

**Comment by davidmdm** [comment]
completed with new context helpers
