### ISSUE TITLE
Restrict Context Access by Project

### ISSUE THREAD

**Issue by eddiewebb** [CircleCI-Public/circle-policy-agent#34]
> Hey! that's my context!

Inside an org with many teams, some will want to restrict contexts to only be used on their projects.

This rule would check and ensure:
- IF they are using a context provided  (function argument)
- AND NOT in our list of project IDs (user side) -- I think user would just `{ not list_of_projects[meta.project_id]}` on the hard_fail stanza?
- THEN FAIL

**Comment by davidmdm** [comment]
Completed with new context helpers
